### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by ghost** [sebadorn/aestas3#4]
Hello dear Developer!

You have a very good blog engine. How to install it?

Thank you! Danke Dir :)

Kardos László

**Comment by sebadorn** [comment]
I'm afraid that is not so easy. I developed it for personal use and never really bothered to include a simple setup. You'd have to do the following:

1) Create a MySQL database, then import the `aestas3.sql` script. This creates the necessary tables.
2) In [`config.php`](https://github.com/sebadorn/aestas3/blob/master/core/config.php) you have to enter your db access info. Also you have to change the `table_prefix` setting to `ae_`.
3) In the table `ae_users` add a row. `u_name_intern` is the login name and `u_pwd` is the password hash. The hash is created with [phpass](https://www.openwall.com/phpass/) (default is 9 iterations).
4) Then you should be able to login under `/admin`.

But be aware that it is really a rather simple CMS. Posts and pages have to be written in HTML, without any editor support. If you want to change the theme, you have to edit the files under `themes/`.

**Comment by sebadorn** [comment]
The following entries have to be added in the database:

```
INSERT INTO `ae_settings` (`s_key`, `s_value`) VALUES
('blog_description', ''),
('blog_title', 'Example'),
('theme', 'standard');
```

```
INSERT INTO `ae_categories` (`ca_id`, `ca_title`, `ca_permalink`, `ca_parent`, `ca_status`) VALUES
(1, 'Uncategorized', 'uncategorized', 0, 'available');
```

And in case you didn't already change it: When adding a user, the default value for `u_status` is `suspended`. This has to be set to `active`.
